### ISSUE TITLE
llama_self_extend_patch_4_36 is not work

### ISSUE THREAD

**Issue by YL-9** [datamllab/LongLM#23]
when I use 4.36.2, it's not work. But if I use 4.32.0, it's work.
I only changed "import llama_self_extend_patch as LlamaSE" in "llama_example.py" to "import llama_self_extend_patch_4_36 as LlamaSE"

**Comment by Mooler0410** [comment]
We found that after 4.36, the default attention of llama changed from "LlamaAttention" to "LlamaSdpaAttention". Hence the replacement function will not work. Instead, you may try:

modify_method_of_instance(base_model, "LlamaAttention", "forward", self_extend_forward)
--> modify_method_of_instance(base_model, "LlamaSdpaAttention", "forward", self_extend_forward)

This might be the reason for the failure.

**Comment by YL-9** [comment]
> We found that after 4.36, the default attention of llama is changed from "LlamaAttention" to "LlamaSdpaAttention". Hence the replacement function will not work. Instead, you may try:
> 
> modify_method_of_instance(base_model, "LlamaAttention", "forward", self_extend_forward) --> modify_method_of_instance(base_model, "LlamaSdpaAttention", "forward", self_extend_forward)
> 
> This might be the reason for the failure.

it work, thank you.
I have another question. I want to add it [here](https://github.com/jquesnelle/yarn). but it can still only run normally on 4.32, and the running result of 4.36 is still wrong.
I just added the following three pieces of code and used this command to run them: CUDA_VISIBLE_DEVICES=0,1 python eval/passkey.py --model /data/supry/models/llama-2/llama2-7b-hf --min-tokens 4096 --max-tokens 8192 --tokens-step 4096 --length-step 1024 --iterations 20 --serope
![MW9`HYFAAUK~T{GVP AJT8S](https://github.com/datamllab/LongLM/assets/73892208/ac8c2bc8-b5f1-4215-b77c-dd37da0523e2)
![~FT7XB3NFIFLJHT%2KFFWSJ](https://github.com/datamllab/LongLM/assets/73892208/ce7832ec-db10-4f78-9dd3-ba04549495d6)
![VFY8E1_DN)BRU1~EL{`~K@I](https://github.com/datamllab/LongLM/assets/73892208/9ddba8a0-c01e-49a4-9f9c-28fb5f18ef42)

**Comment by YL-9** [comment]
![MW9`HYFAAUK~T{GVP AJT8S](https://github.com/datamllab/LongLM/assets/73892208/d11641a4-81bb-4f8e-a311-9c93e144d067)
![$QY)X~9HYTK{2}0 I4K4_W](https://github.com/datamllab/LongLM/assets/73892208/5909801c-ac5c-4360-b85d-e2db13bfaa53)

**Comment by Mooler0410** [comment]
Hi YL-9! Could you please test whether self-extend can work by instance wise modification, like the example we provide? Sometimes, direct modification to the transformers' class does not take effect, while the cause of failure is case by case. That's the reason why we choose to modify the forward function of a model instance rather than its class. (Of course,, this can avoid any unexpected behavior for the modification only happens to the specific model instance)

**Comment by YL-9** [comment]
ok, thank you!

**Comment by ys-zong** [comment]
Hi, thanks for the nice work! I see the current implementation in `llama_self_extend_patch_4_36.py` is regular pytorch. I wonder if you plan to implement Flash attention for `transformers==4.36`?

**Comment by Mooler0410** [comment]
> Hi, thanks for the nice work! I see the current implementation in `llama_self_extend_patch_4_36.py` is regular pytorch. I wonder if you plan to implement Flash attention for `transformers==4.36`?

Hi, thank you for your interests. The main different between transformers==4.36 and transformers==4.38.2 is how the RoPE is applied to KV. You may have a check. The computation of self attention is nearly the same. This means you can follow our 4.38.2 implementation to have a flash attention implementation for 4.36 with minor modification. 

One of the possible issues is the flash_attn version used by 4.36. In that case, you may use our triton flash attention implementation instead of flash_attn. It's 10~20% slower than flash_attn.
